### ISSUE TITLE
type returning value for multiple type set

### ISSUE THREAD

**Issue by jeremenichelli** [WICG/CSS-Parser-API#4]
This is more a question and not an issue, what would `type` return when you have a property set with multiple values like this:

``` js
var styles = window.cssParse.ruleSet(".foo { padding: 5px 0 1em; }");
console.log(styles[0].styleMap.get("padding-left").type) // ?
console.log(styles[0].styleMap.get("padding").type) // ?
```

**Comment by tabatkins** [comment]
Since this API will be covering "generic" parsing (and so doesn't know anything about CSS itself or its properties), you'll get something like:

`[CSSWhitespaceToken, CSSDimensionToken{value:2, unit:"px"}, CSSWhitespaceToken, CSSNumberToken{value:0},CSSWhitespaceToken,  CSSDimensionToken{value:1, unit:"em"}]`

when you ask for the "padding" value. You won't get anything for "padding-left", because the generic parser has no idea what shorthands are.
